# AzureML workspace level
workspace_name: workspace_name
expermient_name: expermient_name
compute_name: compute_name
datastore_name: datastore_name

# subscription level
tenant_id: tenant_id
subscription_id: subscription_id
resource_group: resource_group

# your project parameters
target_col: target_col
